name: google_ml_kit
description: A Flutter plugin to use all APIs from Google's standalone ML Kit for mobile platforms.
version: 0.19.0
homepage: https://github.com/flutter-ml/google_ml_kit_flutter
repository: https://github.com/flutter-ml/google_ml_kit_flutter/tree/master/packages/google_ml_kit

environment:
  sdk: ">=2.16.0 <4.0.0"
  flutter: ">=2.8.0"

dependencies:
  flutter:
    sdk: flutter

  # Vision APIs
  google_mlkit_commons: ^0.9.0
  google_mlkit_face_detection: ^0.12.0
 

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
